package pl.put.poznan.analyzer.commons;

import javax.persistence.*;


/**
 * This class is used to save network in database
 */
@Entity
public class Network {
    /**
     * identifier number in database generated by sequence
     */
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "network_Sequence")
    @SequenceGenerator(name = "network_Sequence", sequenceName = "NETWORK_SEQ")
    private int id;

    /**
     * value of network, list of nodes saved as json
     */
    @Column
    @Lob
    private String jsonValue;

    public int getId() {
        return id;
    }


    public String getJsonValue() {
        return jsonValue;
    }

    public void setJsonValue(String networkJson) {
        this.jsonValue = networkJson;
    }

    /**
     * Class constructor for nodes with connections
     *
     * @param jsonValue value of network, list of nodes saved as json
     */
    public Network(String jsonValue) {
        this.jsonValue = jsonValue;
    }

    /**
     * Empty class constructor
     */
    public Network() {
    }
}
